let questions = [
  {
    numb: 1,
    question: "Which keyword is used to define a function in Python?",
    answer: "def",
    options: ["func", "def", "function", "define"],
  },
  {
    numb: 2,
    question: "Which data type represents True/False in Python?",
    answer: "bool",
    options: ["boolean", "int", "bool", "string"],
  },
  {
    numb: 3,
    question: "Which function is used to display output in Python?",
    answer: "print()",
    options: ["log()", "echo()", "print()", "printf()"],
  },
  {
    numb: 4,
    question: "Which operator is used for exponentiation in Python?",
    answer: "",
    options: ["^", "", "exp()", "power()"],
  },
  {
    numb: 5,
    question: "Which keyword is used for creating a class in Python?",
    answer: "class",
    options: ["object", "class", "struct", "module"],
  },
  {
    numb: 6,
    question: "Which symbol is used to write comments in Python?",
    answer: "#",
    options: ["*", "#", "/* */", "<!-- -->"],
  },
  {
    numb: 7,
    question: "Which data structure is immutable in Python?",
    answer: "tuple",
    options: ["list", "set", "tuple", "dictionary"],
  },
  {
    numb: 8,
    question: "Which method adds an item to a list in Python?",
    answer: "append()",
    options: ["add()", "append()", "push()", "insertAll()"],
  },
  {
    numb: 9,
    question: "Which keyword is used to handle exceptions in Python?",
    answer: "try",
    options: ["catch", "exception", "try", "check"],
  },
  {
    numb: 10,
    question:
      "Which of the following is the correct file extension for Python?",
    answer: ".py",
    options: [".py", ".pyt", ".pt", ".code"],
  },
  {
    numb: 11,
    question: "Django is a framework of which programming language?",
    answer: "Python",
    options: ["Java", "C#", "Python", "PHP"],
  },
  {
    numb: 12,
    question: "Which command is used to create a new Django project?",
    answer: "django-admin startproject",
    options: [
      "django start project",
      "startproject django",
      "django-admin startproject",
      "django new project",
    ],
  },
  {
    numb: 13,
    question: "Which command creates a new app in Django?",
    answer: "django-admin startapp",
    options: [
      "django-admin createapp",
      "django-admin startapp",
      "django startapp",
      "manage.py newapp",
    ],
  },
  {
    numb: 14,
    question: "Which file contains URL configurations in Django?",
    answer: "urls.py",
    options: ["path.py", "views.py", "urls.py", "routes.py"],
  },
  {
    numb: 15,
    question: "Which file is used to define database models in Django?",
    answer: "models.py",
    options: ["database.py", "models.py", "schema.py", "tables.py"],
  },
  {
    numb: 16,
    question: "Which Django command runs the development server?",
    answer: "python manage.py runserver",
    options: [
      "django run",
      "python server",
      "manage.py startserver",
      "python manage.py runserver",
    ],
  },
  {
    numb: 17,
    question: "Which architecture is Django based on?",
    answer: "MVT",
    options: ["MVC", "MVVM", "MVT", "MVP"],
  },
  {
    numb: 18,
    question: "What is Django's default database?",
    answer: "SQLite",
    options: ["MySQL", "MongoDB", "Oracle", "SQLite"],
  },
  {
    numb: 19,
    question: "Which method fetches all objects from a Django model?",
    answer: "objects.all()",
    options: ["get.all()", "all()", "objects.all()", "fetch()"],
  },
  {
    numb: 20,
    question: "Which Django function is used to render HTML templates?",
    answer: "render()",
    options: ["show()", "display()", "render()", "load()"],
  },
  {
    numb: 21,
    question: "Where should HTML templates be stored in a Django app?",
    answer: "templates folder",
    options: [
      "static folder",
      "templates folder",
      "views folder",
      "public folder",
    ],
  },
  {
    numb: 22,
    question: "Which folder stores CSS and JS files in Django?",
    answer: "static",
    options: ["assets", "public", "static", "templates"],
  },
  {
    numb: 23,
    question: "Which command applies database migrations in Django?",
    answer: "python manage.py migrate",
    options: [
      "django migrate",
      "python migrate",
      "python manage.py migrate",
      "manage.py apply",
    ],
  },
  {
    numb: 24,
    question: "Which file contains Django project settings?",
    answer: "settings.py",
    options: ["config.py", "settings.py", "main.py", "system.py"],
  },
  {
    numb: 25,
    question: "Which keyword is used to import a module in Python?",
    answer: "import",
    options: ["include", "import", "require", "load"],
  },
];
